FROM xfce:base

# Update package index
RUN apt-get update

ENV DEBIAN_FRONTEND=noninteractive

ARG PROXY=""
ENV http_proxy=$PROXY https_proxy=$PROXY

# Install systemd as the init system
RUN apt-get install -y systemd-sysv

# Tools for adding APT repositories and handling GPG keys
RUN apt-get install -y software-properties-common gnupg

# Install OpenSSH for remote access
RUN apt-get install -y openssh-server openssh-client

# GPU-related libraries (DRM, GLX)
RUN apt-get install -y libglx-mesa0 libdrm2

# Install Xdummy
RUN apt-get install -y xserver-xorg-video-dummy

# VNC components (x11vnc server, noVNC, stunnel for TLS support, tigervnc)
RUN apt-get install -y \
    x11vnc \
    novnc \
    stunnel \
    tigervnc-standalone-server \
    tigervnc-common

# RDP support
RUN apt-get install -y xrdp

# Common utilities and base system tools
RUN apt-get install -y \
    sudo \
    iproute2 \
    vim \
    iputils-ping \
    dnsutils \
    curl \
    wget \
    unzip \
    catimg \
    git \
    pavucontrol \
    htop \
    ristretto \
    parole \
    pkg-config \
    tree

# Install input method framework (ibus + libpinyin for Chinese input)
RUN apt-get install -y ibus ibus-libpinyin

# Add Mozilla APT repository and configure package priority
RUN install -d -m 0755 /etc/apt/keyrings && \
    wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null && \
    echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null && \
    echo "Package: *\n\
    Pin: origin packages.mozilla.org\n\
    Pin-Priority: 1000" | sudo tee /etc/apt/preferences.d/mozilla

# Install Firefox and its related runtime dependencies
RUN apt-get update && apt-get install -y dirmngr \
    apulse \
        ca-certificates \
        ffmpeg \
        firefox \
        hicolor-icon-theme \
        libasound2 \
        libgl1-mesa-dri \
        libgl1-mesa-glx \
        fonts-noto \
        fonts-noto-cjk \
        fonts-noto-color-emoji

# Install VSCode
RUN echo "code code/add-microsoft-repo boolean true" | sudo debconf-set-selections
RUN apt-get install gpg
RUN wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg && \
        install -D -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/microsoft.gpg && \
        rm -f microsoft.gpg

RUN echo "Types: deb\n\
URIs: https://packages.microsoft.com/repos/code\n\
Suites: stable\n\
Components: main\n\
Architectures: amd64,arm64,armhf\n\
Signed-By: /usr/share/keyrings/microsoft.gpg\n\
" > /etc/apt/sources.list.d/vscode.sources

RUN apt-get install apt-transport-https
RUN apt-get update
# or code-insiders
RUN apt-get install code

ENV DEBIAN_FRONTEND= http_proxy= https_proxy=
